/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* src = "rtl/adder_tree.sv:11.1-24.10" *)
module adder_tree(p0, p1, p2, p3, sum);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  (* src = "rtl/adder_tree.sv:12.25-12.27" *)
  input [15:0] p0;
  wire [15:0] p0;
  (* src = "rtl/adder_tree.sv:13.25-13.27" *)
  input [15:0] p1;
  wire [15:0] p1;
  (* src = "rtl/adder_tree.sv:14.25-14.27" *)
  input [15:0] p2;
  wire [15:0] p2;
  (* src = "rtl/adder_tree.sv:15.25-15.27" *)
  input [15:0] p3;
  wire [15:0] p3;
  (* src = "rtl/adder_tree.sv:16.25-16.28" *)
  output [31:0] sum;
  wire [31:0] sum;
  assign _235_ = ~p3[0];
  assign _236_ = ~(p1[0] ^ p0[0]);
  assign _237_ = _236_ ^ p2[0];
  assign sum[0] = _237_ ^ _235_;
  assign _238_ = ~(p1[2] ^ p0[2]);
  assign _239_ = _238_ ^ p2[2];
  assign _240_ = ~(p1[1] & p0[1]);
  assign _241_ = ~(p1[1] ^ p0[1]);
  assign _242_ = p2[1] & ~(_241_);
  assign _243_ = _240_ & ~(_242_);
  assign _244_ = ~(_243_ ^ _239_);
  assign _245_ = _244_ ^ p3[2];
  assign _246_ = ~(_241_ ^ p2[1]);
  assign _247_ = ~(p1[0] & p0[0]);
  assign _248_ = p2[0] & ~(_236_);
  assign _249_ = _247_ & ~(_248_);
  assign _250_ = _249_ | ~(_246_);
  assign _000_ = _249_ ^ _246_;
  assign _001_ = p3[1] & ~(_000_);
  assign _002_ = _250_ & ~(_001_);
  assign _003_ = ~(_002_ ^ _245_);
  assign _004_ = ~(_000_ ^ p3[1]);
  assign _005_ = _237_ | _235_;
  assign _006_ = _004_ & ~(_005_);
  assign sum[2] = ~(_006_ ^ _003_);
  assign _007_ = ~(p1[3] ^ p0[3]);
  assign _008_ = _007_ ^ p2[3];
  assign _009_ = ~(p1[2] & p0[2]);
  assign _010_ = p2[2] & ~(_238_);
  assign _011_ = _009_ & ~(_010_);
  assign _012_ = ~(_011_ ^ _008_);
  assign _013_ = ~(_012_ ^ p3[3]);
  assign _014_ = _243_ | _239_;
  assign _015_ = p3[2] & ~(_244_);
  assign _016_ = _014_ & ~(_015_);
  assign _017_ = _016_ ^ _013_;
  assign _018_ = _002_ | _245_;
  assign _019_ = _006_ & ~(_003_);
  assign _020_ = _018_ & ~(_019_);
  assign sum[3] = _020_ ^ _017_;
  assign _021_ = ~(p1[4] ^ p0[4]);
  assign _022_ = _021_ ^ p2[4];
  assign _023_ = ~(p1[3] & p0[3]);
  assign _024_ = p2[3] & ~(_007_);
  assign _025_ = _023_ & ~(_024_);
  assign _026_ = ~(_025_ ^ _022_);
  assign _027_ = _026_ ^ p3[4];
  assign _028_ = _011_ | _008_;
  assign _029_ = p3[3] & ~(_012_);
  assign _030_ = _028_ & ~(_029_);
  assign _031_ = ~(_030_ ^ _027_);
  assign _032_ = _013_ & ~(_016_);
  assign _033_ = ~(_018_ | _017_);
  assign _034_ = _033_ | _032_;
  assign _035_ = _017_ | _003_;
  assign _036_ = _006_ & ~(_035_);
  assign _037_ = _036_ | _034_;
  assign sum[4] = ~(_037_ ^ _031_);
  assign _038_ = ~(p1[5] ^ p0[5]);
  assign _039_ = _038_ ^ p2[5];
  assign _040_ = ~(p1[4] & p0[4]);
  assign _041_ = p2[4] & ~(_021_);
  assign _042_ = _040_ & ~(_041_);
  assign _043_ = ~(_042_ ^ _039_);
  assign _044_ = ~(_043_ ^ p3[5]);
  assign _045_ = _025_ | _022_;
  assign _046_ = p3[4] & ~(_026_);
  assign _047_ = _045_ & ~(_046_);
  assign _048_ = _047_ ^ _044_;
  assign _049_ = _030_ | _027_;
  assign _050_ = _037_ & ~(_031_);
  assign _051_ = _049_ & ~(_050_);
  assign sum[5] = _051_ ^ _048_;
  assign _052_ = ~(p1[6] ^ p0[6]);
  assign _053_ = _052_ ^ p2[6];
  assign _054_ = ~(p1[5] & p0[5]);
  assign _055_ = p2[5] & ~(_038_);
  assign _056_ = _054_ & ~(_055_);
  assign _057_ = ~(_056_ ^ _053_);
  assign _058_ = _057_ ^ p3[6];
  assign _059_ = _042_ | _039_;
  assign _060_ = p3[5] & ~(_043_);
  assign _061_ = _059_ & ~(_060_);
  assign _062_ = ~(_061_ ^ _058_);
  assign _063_ = _044_ & ~(_047_);
  assign _064_ = ~(_049_ | _048_);
  assign _065_ = _064_ | _063_;
  assign _066_ = _048_ | _031_;
  assign _067_ = _066_ | ~(_037_);
  assign _068_ = _067_ & ~(_065_);
  assign sum[6] = _068_ ^ _062_;
  assign _069_ = ~(p1[7] ^ p0[7]);
  assign _070_ = _069_ ^ p2[7];
  assign _071_ = ~(p1[6] & p0[6]);
  assign _072_ = p2[6] & ~(_052_);
  assign _073_ = _071_ & ~(_072_);
  assign _074_ = ~(_073_ ^ _070_);
  assign _075_ = ~(_074_ ^ p3[7]);
  assign _076_ = _056_ | _053_;
  assign _077_ = p3[6] & ~(_057_);
  assign _078_ = _076_ & ~(_077_);
  assign _079_ = _078_ ^ _075_;
  assign _080_ = _061_ | _058_;
  assign _081_ = ~(_068_ | _062_);
  assign _082_ = _080_ & ~(_081_);
  assign sum[7] = _082_ ^ _079_;
  assign _083_ = ~(p1[8] ^ p0[8]);
  assign _084_ = _083_ ^ p2[8];
  assign _085_ = ~(p1[7] & p0[7]);
  assign _086_ = p2[7] & ~(_069_);
  assign _087_ = _085_ & ~(_086_);
  assign _088_ = ~(_087_ ^ _084_);
  assign _089_ = _088_ ^ p3[8];
  assign _090_ = _073_ | _070_;
  assign _091_ = p3[7] & ~(_074_);
  assign _092_ = _090_ & ~(_091_);
  assign _093_ = ~(_092_ ^ _089_);
  assign _094_ = _075_ & ~(_078_);
  assign _095_ = ~(_080_ | _079_);
  assign _096_ = _095_ | _094_;
  assign _097_ = _079_ | _062_;
  assign _098_ = _065_ & ~(_097_);
  assign _099_ = ~(_098_ | _096_);
  assign _100_ = _097_ | _066_;
  assign _101_ = _037_ & ~(_100_);
  assign _102_ = _101_ | ~(_099_);
  assign sum[8] = ~(_102_ ^ _093_);
  assign _103_ = ~(p1[9] ^ p0[9]);
  assign _104_ = ~(_103_ ^ p2[9]);
  assign _105_ = ~(p1[8] & p0[8]);
  assign _106_ = p2[8] & ~(_083_);
  assign _107_ = _105_ & ~(_106_);
  assign _108_ = _107_ ^ _104_;
  assign _109_ = ~(_108_ ^ p3[9]);
  assign _110_ = _087_ | _084_;
  assign _111_ = p3[8] & ~(_088_);
  assign _112_ = _110_ & ~(_111_);
  assign _113_ = _112_ ^ _109_;
  assign _114_ = _092_ | _089_;
  assign _115_ = _102_ & ~(_093_);
  assign _116_ = _114_ & ~(_115_);
  assign sum[9] = _116_ ^ _113_;
  assign _117_ = ~(p1[10] ^ p0[10]);
  assign _118_ = ~(_117_ ^ p2[10]);
  assign _119_ = ~(p1[9] & p0[9]);
  assign _120_ = p2[9] & ~(_103_);
  assign _121_ = _119_ & ~(_120_);
  assign _122_ = _121_ ^ _118_;
  assign _123_ = _122_ ^ p3[10];
  assign _124_ = _107_ | ~(_104_);
  assign _125_ = p3[9] & ~(_108_);
  assign _126_ = _124_ & ~(_125_);
  assign _127_ = ~(_126_ ^ _123_);
  assign _128_ = _109_ & ~(_112_);
  assign _129_ = ~(_114_ | _113_);
  assign _130_ = _129_ | _128_;
  assign _131_ = _113_ | _093_;
  assign _132_ = _131_ | ~(_102_);
  assign _133_ = _132_ & ~(_130_);
  assign sum[10] = _133_ ^ _127_;
  assign _134_ = ~(p1[11] ^ p0[11]);
  assign _135_ = _134_ ^ p2[11];
  assign _136_ = ~(p1[10] & p0[10]);
  assign _137_ = p2[10] & ~(_117_);
  assign _138_ = _136_ & ~(_137_);
  assign _139_ = ~(_138_ ^ _135_);
  assign _140_ = ~(_139_ ^ p3[11]);
  assign _141_ = _121_ | ~(_118_);
  assign _142_ = p3[10] & ~(_122_);
  assign _143_ = _141_ & ~(_142_);
  assign _144_ = _143_ ^ _140_;
  assign _145_ = _126_ | _123_;
  assign _146_ = ~(_133_ | _127_);
  assign _147_ = _145_ & ~(_146_);
  assign sum[11] = _147_ ^ _144_;
  assign _148_ = ~(p1[12] ^ p0[12]);
  assign _149_ = _148_ ^ p2[12];
  assign _150_ = ~(p1[11] & p0[11]);
  assign _151_ = p2[11] & ~(_134_);
  assign _152_ = _150_ & ~(_151_);
  assign _153_ = ~(_152_ ^ _149_);
  assign _154_ = _153_ ^ p3[12];
  assign _155_ = _138_ | _135_;
  assign _156_ = p3[11] & ~(_139_);
  assign _157_ = _155_ & ~(_156_);
  assign _158_ = ~(_157_ ^ _154_);
  assign _159_ = _140_ & ~(_143_);
  assign _160_ = ~(_145_ | _144_);
  assign _161_ = _160_ | _159_;
  assign _162_ = _144_ | _127_;
  assign _163_ = _130_ & ~(_162_);
  assign _164_ = _163_ | _161_;
  assign _165_ = _162_ | _131_;
  assign _166_ = _102_ & ~(_165_);
  assign _167_ = ~(_166_ | _164_);
  assign sum[12] = _167_ ^ _158_;
  assign _168_ = ~(p1[13] ^ p0[13]);
  assign _169_ = _168_ ^ p2[13];
  assign _170_ = ~(p1[12] & p0[12]);
  assign _171_ = p2[12] & ~(_148_);
  assign _172_ = _170_ & ~(_171_);
  assign _173_ = ~(_172_ ^ _169_);
  assign _174_ = _173_ ^ p3[13];
  assign _175_ = _152_ | _149_;
  assign _176_ = p3[12] & ~(_153_);
  assign _177_ = _175_ & ~(_176_);
  assign _178_ = _177_ ^ _174_;
  assign _179_ = _157_ | _154_;
  assign _180_ = ~(_167_ | _158_);
  assign _181_ = _180_ | ~(_179_);
  assign sum[13] = _181_ ^ _178_;
  assign _182_ = ~(p1[14] ^ p0[14]);
  assign _183_ = _182_ ^ p2[14];
  assign _184_ = ~(p1[13] & p0[13]);
  assign _185_ = p2[13] & ~(_168_);
  assign _186_ = _184_ & ~(_185_);
  assign _187_ = ~(_186_ ^ _183_);
  assign _188_ = _187_ ^ p3[14];
  assign _189_ = _172_ | _169_;
  assign _190_ = p3[13] & ~(_173_);
  assign _191_ = _189_ & ~(_190_);
  assign _192_ = ~(_191_ ^ _188_);
  assign _193_ = ~(_177_ | _174_);
  assign _194_ = _178_ & ~(_179_);
  assign _195_ = _194_ | _193_;
  assign _196_ = _158_ | ~(_178_);
  assign _197_ = _196_ | _167_;
  assign _198_ = _197_ & ~(_195_);
  assign sum[14] = _198_ ^ _192_;
  assign _199_ = ~(p1[15] ^ p0[15]);
  assign _200_ = _199_ ^ p2[15];
  assign _201_ = ~(p1[14] & p0[14]);
  assign _202_ = p2[14] & ~(_182_);
  assign _203_ = _201_ & ~(_202_);
  assign _204_ = ~(_203_ ^ _200_);
  assign _205_ = _204_ ^ p3[15];
  assign _206_ = _186_ | _183_;
  assign _207_ = p3[14] & ~(_187_);
  assign _208_ = _206_ & ~(_207_);
  assign _209_ = ~(_208_ ^ _205_);
  assign _210_ = _191_ | _188_;
  assign _211_ = ~(_198_ | _192_);
  assign _212_ = _210_ & ~(_211_);
  assign sum[15] = _212_ ^ _209_;
  assign _213_ = p1[15] & p0[15];
  assign _214_ = p2[15] & ~(_199_);
  assign _215_ = ~(_214_ | _213_);
  assign _216_ = ~_215_;
  assign _217_ = _203_ | _200_;
  assign _218_ = p3[15] & ~(_204_);
  assign _219_ = _217_ & ~(_218_);
  assign _220_ = _219_ ^ _216_;
  assign _221_ = _208_ | _205_;
  assign _222_ = ~(_210_ | _209_);
  assign _223_ = _221_ & ~(_222_);
  assign _224_ = _209_ | _192_;
  assign _225_ = _195_ & ~(_224_);
  assign _226_ = _223_ & ~(_225_);
  assign _227_ = _224_ | _196_;
  assign _228_ = _164_ & ~(_227_);
  assign _229_ = _226_ & ~(_228_);
  assign _230_ = _227_ | _165_;
  assign _231_ = _102_ & ~(_230_);
  assign _232_ = _229_ & ~(_231_);
  assign sum[16] = _232_ ^ _220_;
  assign sum[1] = ~(_005_ ^ _004_);
  assign _233_ = _216_ & ~(_219_);
  assign _234_ = ~(_232_ | _220_);
  assign sum[17] = _234_ | _233_;
  assign sum[31:18] = 14'h0000;
endmodule

(* src = "rtl/control_fsm.sv:12.1-67.10" *)
module control_fsm(clk, rst_n, start, result_en, done);
  wire _0_;
  (* src = "rtl/control_fsm.sv:13.18-13.21" *)
  input clk;
  wire clk;
  (* enum_type = "$enum0" *)
  (* enum_value_00 = "\\IDLE" *)
  (* enum_value_01 = "\\DONE" *)
  (* src = "rtl/control_fsm.sv:26.13-26.26" *)
  (* wiretype = "\\state_t" *)
  wire [1:0] current_state;
  (* src = "rtl/control_fsm.sv:18.18-18.22" *)
  output done;
  wire done;
  (* enum_type = "$enum0" *)
  (* enum_value_00 = "\\IDLE" *)
  (* enum_value_01 = "\\DONE" *)
  (* src = "rtl/control_fsm.sv:27.13-27.23" *)
  (* wiretype = "\\state_t" *)
  wire [1:0] next_state;
  (* src = "rtl/control_fsm.sv:17.18-17.27" *)
  output result_en;
  wire result_en;
  (* src = "rtl/control_fsm.sv:14.18-14.23" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/control_fsm.sv:15.18-15.23" *)
  input start;
  wire start;
  assign _0_ = current_state[0] | start;
  assign next_state[0] = ~current_state[0];
  assign result_en = start & ~(current_state[0]);
  reg \current_state_reg[0] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/control_fsm.sv:30.5-36.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \current_state_reg[0]  <= 1'h0;
    else if (_0_) \current_state_reg[0]  <= next_state[0];
  assign current_state[0] = \current_state_reg[0] ;
  assign current_state[1] = 1'h0;
  assign done = current_state[0];
  assign next_state[1] = 1'h0;
endmodule

(* src = "rtl/mac_unit.sv:11.1-19.10" *)
module mac_unit(a, b, product);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  (* src = "rtl/mac_unit.sv:12.25-12.26" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "rtl/mac_unit.sv:13.25-13.26" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "rtl/mac_unit.sv:14.25-14.32" *)
  output [15:0] product;
  wire [15:0] product;
  assign product[0] = b[0] & a[0];
  assign _234_ = a[1] & b[0];
  assign _244_ = b[1] & a[0];
  assign product[1] = _244_ ^ _234_;
  assign _264_ = a[2] & b[0];
  assign _275_ = b[1] & a[1];
  assign _280_ = _275_ ^ _264_;
  assign _281_ = b[2] & a[0];
  assign _282_ = ~_281_;
  assign _283_ = _282_ ^ _280_;
  assign _284_ = _244_ & _234_;
  assign product[2] = ~(_284_ ^ _283_);
  assign _285_ = ~(a[3] & b[0]);
  assign _286_ = ~(b[1] & a[2]);
  assign _287_ = _286_ ^ _285_;
  assign _288_ = ~(b[2] & a[1]);
  assign _289_ = _288_ ^ _287_;
  assign _290_ = ~(_275_ & _264_);
  assign _291_ = _280_ & ~(_282_);
  assign _292_ = _290_ & ~(_291_);
  assign _293_ = _292_ ^ _289_;
  assign _294_ = b[3] & a[0];
  assign _295_ = ~_294_;
  assign _296_ = _295_ ^ _293_;
  assign _297_ = _284_ & ~(_283_);
  assign product[3] = ~(_297_ ^ _296_);
  assign _298_ = ~(a[4] & b[0]);
  assign _299_ = ~(b[1] & a[3]);
  assign _300_ = _299_ ^ _298_;
  assign _301_ = ~(b[2] & a[2]);
  assign _302_ = _301_ ^ _300_;
  assign _303_ = _286_ | _285_;
  assign _304_ = _287_ & ~(_288_);
  assign _305_ = _303_ & ~(_304_);
  assign _306_ = _305_ ^ _302_;
  assign _307_ = b[3] & a[1];
  assign _308_ = b[4] & a[0];
  assign _309_ = ~(_308_ ^ _307_);
  assign _310_ = _309_ ^ _306_;
  assign _311_ = _292_ | _289_;
  assign _312_ = _293_ & ~(_295_);
  assign _313_ = _311_ & ~(_312_);
  assign _314_ = ~(_313_ ^ _310_);
  assign _315_ = _297_ & ~(_296_);
  assign product[4] = ~(_315_ ^ _314_);
  assign _316_ = ~(a[6] & b[0]);
  assign _317_ = ~(b[1] & a[5]);
  assign _318_ = _317_ ^ _316_;
  assign _319_ = ~(b[2] & a[4]);
  assign _320_ = _319_ ^ _318_;
  assign _321_ = ~(a[5] & b[0]);
  assign _322_ = b[1] & a[4];
  assign _323_ = _321_ | ~(_322_);
  assign _324_ = b[2] & a[3];
  assign _325_ = _322_ ^ _321_;
  assign _326_ = _324_ & ~(_325_);
  assign _327_ = _323_ & ~(_326_);
  assign _328_ = _327_ ^ _320_;
  assign _329_ = b[3] & a[3];
  assign _330_ = b[4] & a[2];
  assign _331_ = _330_ ^ _329_;
  assign _332_ = ~(b[5] & a[1]);
  assign _333_ = _332_ ^ _331_;
  assign _334_ = _333_ ^ _328_;
  assign _335_ = ~(_325_ ^ _324_);
  assign _336_ = _299_ | _298_;
  assign _337_ = _300_ & ~(_301_);
  assign _000_ = _336_ & ~(_337_);
  assign _001_ = _000_ | ~(_335_);
  assign _002_ = b[3] & a[2];
  assign _003_ = b[4] & a[1];
  assign _004_ = _003_ ^ _002_;
  assign _005_ = b[5] & a[0];
  assign _006_ = _005_ ^ _004_;
  assign _007_ = _000_ ^ _335_;
  assign _008_ = _006_ & ~(_007_);
  assign _009_ = _001_ & ~(_008_);
  assign _010_ = _009_ ^ _334_;
  assign _011_ = ~(_003_ & _002_);
  assign _012_ = _005_ & _004_;
  assign _013_ = _011_ & ~(_012_);
  assign _014_ = b[6] & a[0];
  assign _015_ = _014_ ^ _013_;
  assign _016_ = ~(_015_ ^ _010_);
  assign _017_ = ~(_007_ ^ _006_);
  assign _018_ = _305_ | _302_;
  assign _019_ = _306_ & ~(_309_);
  assign _020_ = _018_ & ~(_019_);
  assign _021_ = _020_ | ~(_017_);
  assign _022_ = _308_ & _307_;
  assign _023_ = _020_ ^ _017_;
  assign _024_ = _022_ & ~(_023_);
  assign _025_ = _021_ & ~(_024_);
  assign _026_ = _025_ ^ _016_;
  assign _027_ = _023_ ^ _022_;
  assign _028_ = _313_ | _310_;
  assign _029_ = _028_ | _027_;
  assign _030_ = ~(_029_ ^ _026_);
  assign _031_ = _028_ ^ _027_;
  assign _032_ = _315_ & ~(_314_);
  assign _033_ = _032_ & _031_;
  assign product[6] = ~(_033_ ^ _030_);
  assign _034_ = ~(a[7] & b[0]);
  assign _035_ = ~(b[1] & a[6]);
  assign _036_ = _035_ ^ _034_;
  assign _037_ = ~(b[2] & a[5]);
  assign _038_ = _037_ ^ _036_;
  assign _039_ = _317_ | _316_;
  assign _040_ = _318_ & ~(_319_);
  assign _041_ = _039_ & ~(_040_);
  assign _042_ = _041_ ^ _038_;
  assign _043_ = b[3] & a[4];
  assign _044_ = b[4] & a[3];
  assign _045_ = _044_ ^ _043_;
  assign _046_ = ~(b[5] & a[2]);
  assign _047_ = _046_ ^ _045_;
  assign _048_ = _047_ ^ _042_;
  assign _049_ = _327_ | _320_;
  assign _050_ = _328_ & ~(_333_);
  assign _051_ = _049_ & ~(_050_);
  assign _052_ = _051_ ^ _048_;
  assign _053_ = ~(_330_ & _329_);
  assign _054_ = _331_ & ~(_332_);
  assign _055_ = _053_ & ~(_054_);
  assign _056_ = b[6] & a[1];
  assign _057_ = ~_056_;
  assign _058_ = _057_ ^ _055_;
  assign _059_ = b[7] & a[0];
  assign _060_ = ~_059_;
  assign _061_ = _060_ ^ _058_;
  assign _062_ = _061_ ^ _052_;
  assign _063_ = _009_ | _334_;
  assign _064_ = _010_ & ~(_015_);
  assign _065_ = _063_ & ~(_064_);
  assign _066_ = _065_ ^ _062_;
  assign _067_ = _014_ & ~(_013_);
  assign _068_ = ~_067_;
  assign _069_ = _068_ ^ _066_;
  assign _070_ = _016_ & ~(_025_);
  assign _071_ = _070_ ^ _069_;
  assign _072_ = _029_ | _026_;
  assign _073_ = _033_ & ~(_030_);
  assign _074_ = _072_ & ~(_073_);
  assign product[7] = _074_ ^ _071_;
  assign _075_ = ~(b[1] & a[7]);
  assign _076_ = b[2] & a[6];
  assign _077_ = _076_ ^ _075_;
  assign _078_ = _035_ | _034_;
  assign _079_ = _036_ & ~(_037_);
  assign _080_ = _078_ & ~(_079_);
  assign _081_ = _080_ ^ _077_;
  assign _082_ = b[3] & a[5];
  assign _083_ = b[4] & a[4];
  assign _084_ = _083_ ^ _082_;
  assign _085_ = ~(b[5] & a[3]);
  assign _086_ = _085_ ^ _084_;
  assign _087_ = _086_ ^ _081_;
  assign _088_ = _041_ | _038_;
  assign _089_ = _042_ & ~(_047_);
  assign _090_ = _088_ & ~(_089_);
  assign _091_ = _090_ ^ _087_;
  assign _092_ = ~(_044_ & _043_);
  assign _093_ = _045_ & ~(_046_);
  assign _094_ = _092_ & ~(_093_);
  assign _095_ = b[6] & a[2];
  assign _096_ = _095_ ^ _094_;
  assign _097_ = b[7] & a[1];
  assign _098_ = _097_ ^ _096_;
  assign _099_ = _098_ ^ _091_;
  assign _100_ = _051_ | _048_;
  assign _101_ = _052_ & ~(_061_);
  assign _102_ = _100_ & ~(_101_);
  assign _103_ = _102_ ^ _099_;
  assign _104_ = _057_ | _055_;
  assign _105_ = _058_ & ~(_060_);
  assign _106_ = _104_ & ~(_105_);
  assign _107_ = _106_ ^ _103_;
  assign _108_ = _065_ | _062_;
  assign _109_ = _066_ & ~(_068_);
  assign _110_ = _108_ & ~(_109_);
  assign _111_ = ~(_110_ ^ _107_);
  assign _112_ = _070_ & ~(_069_);
  assign _113_ = ~(_072_ | _071_);
  assign _114_ = _113_ | _112_;
  assign _115_ = _071_ | _030_;
  assign _116_ = _033_ & ~(_115_);
  assign _117_ = _116_ | _114_;
  assign product[8] = ~(_117_ ^ _111_);
  assign _118_ = b[2] & a[7];
  assign _119_ = _076_ & ~(_075_);
  assign _120_ = _119_ ^ _118_;
  assign _121_ = b[3] & a[6];
  assign _122_ = b[4] & a[5];
  assign _123_ = _122_ ^ _121_;
  assign _124_ = b[5] & a[4];
  assign _125_ = ~_124_;
  assign _126_ = _125_ ^ _123_;
  assign _127_ = _126_ ^ _120_;
  assign _128_ = _080_ | _077_;
  assign _129_ = _081_ & ~(_086_);
  assign _130_ = _128_ & ~(_129_);
  assign _131_ = _130_ ^ _127_;
  assign _132_ = ~(_083_ & _082_);
  assign _133_ = _084_ & ~(_085_);
  assign _134_ = _132_ & ~(_133_);
  assign _135_ = b[6] & a[3];
  assign _136_ = _135_ ^ _134_;
  assign _137_ = b[7] & a[2];
  assign _138_ = _137_ ^ _136_;
  assign _139_ = _138_ ^ _131_;
  assign _140_ = _090_ | _087_;
  assign _141_ = _091_ & ~(_098_);
  assign _142_ = _140_ & ~(_141_);
  assign _143_ = _142_ ^ _139_;
  assign _144_ = _094_ | ~(_095_);
  assign _145_ = _097_ & ~(_096_);
  assign _146_ = _144_ & ~(_145_);
  assign _147_ = ~(_146_ ^ _143_);
  assign _148_ = _102_ | _099_;
  assign _149_ = _103_ & ~(_106_);
  assign _150_ = _148_ & ~(_149_);
  assign _151_ = _150_ ^ _147_;
  assign _152_ = _110_ | _107_;
  assign _153_ = _117_ & ~(_111_);
  assign _154_ = _152_ & ~(_153_);
  assign product[9] = _154_ ^ _151_;
  assign _155_ = b[3] & a[7];
  assign _156_ = b[4] & a[6];
  assign _157_ = ~(_156_ ^ _155_);
  assign _158_ = b[5] & a[5];
  assign _159_ = _158_ ^ _157_;
  assign _160_ = ~(_119_ & _118_);
  assign _161_ = _120_ & ~(_126_);
  assign _162_ = _160_ & ~(_161_);
  assign _163_ = _162_ ^ _159_;
  assign _164_ = _122_ & _121_;
  assign _165_ = _123_ & ~(_125_);
  assign _166_ = ~(_165_ | _164_);
  assign _167_ = b[6] & a[4];
  assign _168_ = _167_ ^ _166_;
  assign _169_ = b[7] & a[3];
  assign _170_ = _169_ ^ _168_;
  assign _171_ = _170_ ^ _163_;
  assign _172_ = _130_ | _127_;
  assign _173_ = _131_ & ~(_138_);
  assign _174_ = _172_ & ~(_173_);
  assign _175_ = _174_ ^ _171_;
  assign _176_ = _134_ | ~(_135_);
  assign _177_ = _137_ & ~(_136_);
  assign _178_ = _176_ & ~(_177_);
  assign _179_ = _178_ ^ _175_;
  assign _180_ = _142_ | _139_;
  assign _181_ = _143_ & ~(_146_);
  assign _182_ = _180_ & ~(_181_);
  assign _183_ = ~(_182_ ^ _179_);
  assign _184_ = _147_ & ~(_150_);
  assign _185_ = ~(_152_ | _151_);
  assign _186_ = _185_ | _184_;
  assign _187_ = _151_ | _111_;
  assign _188_ = _187_ | ~(_117_);
  assign _189_ = _188_ & ~(_186_);
  assign product[10] = _189_ ^ _183_;
  assign _190_ = b[4] & a[7];
  assign _191_ = b[5] & a[6];
  assign _192_ = ~(_191_ ^ _190_);
  assign _193_ = ~_192_;
  assign _194_ = _156_ & _155_;
  assign _195_ = _158_ & ~(_157_);
  assign _196_ = ~(_195_ | _194_);
  assign _197_ = b[6] & a[5];
  assign _198_ = _197_ ^ _196_;
  assign _199_ = b[7] & a[4];
  assign _200_ = _199_ ^ _198_;
  assign _201_ = _200_ ^ _193_;
  assign _202_ = _162_ | _159_;
  assign _203_ = _163_ & ~(_170_);
  assign _204_ = _202_ & ~(_203_);
  assign _205_ = _204_ ^ _201_;
  assign _206_ = _166_ | ~(_167_);
  assign _207_ = _169_ & ~(_168_);
  assign _208_ = _206_ & ~(_207_);
  assign _209_ = _208_ ^ _205_;
  assign _210_ = _174_ | _171_;
  assign _211_ = _175_ & ~(_178_);
  assign _212_ = _210_ & ~(_211_);
  assign _213_ = ~(_212_ ^ _209_);
  assign _214_ = _182_ | _179_;
  assign _215_ = ~(_189_ | _183_);
  assign _216_ = _214_ & ~(_215_);
  assign product[11] = _216_ ^ _213_;
  assign _217_ = b[5] & a[7];
  assign _218_ = _191_ & _190_;
  assign _219_ = b[6] & a[6];
  assign _220_ = ~(_219_ ^ _218_);
  assign _221_ = b[7] & a[5];
  assign _222_ = _221_ ^ _220_;
  assign _223_ = _222_ ^ _217_;
  assign _224_ = _193_ & ~(_200_);
  assign _225_ = _224_ ^ _223_;
  assign _226_ = _196_ | ~(_197_);
  assign _227_ = _199_ & ~(_198_);
  assign _228_ = _226_ & ~(_227_);
  assign _229_ = ~(_228_ ^ _225_);
  assign _230_ = _204_ | _201_;
  assign _231_ = _205_ & ~(_208_);
  assign _232_ = _230_ & ~(_231_);
  assign _233_ = ~(_232_ ^ _229_);
  assign _235_ = _212_ | _209_;
  assign _236_ = ~(_214_ | _213_);
  assign _237_ = _235_ & ~(_236_);
  assign _238_ = _213_ | _183_;
  assign _239_ = _186_ & ~(_238_);
  assign _240_ = _237_ & ~(_239_);
  assign _241_ = _238_ | _187_;
  assign _242_ = _117_ & ~(_241_);
  assign _243_ = _240_ & ~(_242_);
  assign product[12] = _243_ ^ _233_;
  assign _245_ = b[6] & a[7];
  assign _246_ = b[7] & a[6];
  assign _247_ = ~(_246_ ^ _245_);
  assign _248_ = _217_ & ~(_222_);
  assign _249_ = _248_ ^ _247_;
  assign _250_ = ~(_219_ & _218_);
  assign _251_ = _221_ & ~(_220_);
  assign _252_ = _250_ & ~(_251_);
  assign _253_ = ~(_252_ ^ _249_);
  assign _254_ = _223_ | ~(_224_);
  assign _255_ = ~(_228_ | _225_);
  assign _256_ = _254_ & ~(_255_);
  assign _257_ = ~(_256_ ^ _253_);
  assign _258_ = _232_ | _229_;
  assign _259_ = ~(_243_ | _233_);
  assign _260_ = _258_ & ~(_259_);
  assign product[13] = _260_ ^ _257_;
  assign _261_ = b[7] & a[7];
  assign _262_ = _246_ & _245_;
  assign _263_ = ~(_262_ ^ _261_);
  assign _265_ = _247_ | ~(_248_);
  assign _266_ = ~(_252_ | _249_);
  assign _267_ = _265_ & ~(_266_);
  assign _268_ = ~(_267_ ^ _263_);
  assign _269_ = _256_ | _253_;
  assign _270_ = ~(_258_ | _257_);
  assign _271_ = _269_ & ~(_270_);
  assign _272_ = _257_ | _233_;
  assign _273_ = ~(_272_ | _243_);
  assign _274_ = _271_ & ~(_273_);
  assign product[14] = _274_ ^ _268_;
  assign _276_ = ~(_262_ & _261_);
  assign _277_ = _267_ | _263_;
  assign _278_ = ~(_274_ | _268_);
  assign _279_ = _277_ & ~(_278_);
  assign product[15] = _279_ ^ _276_;
  assign product[5] = _032_ ^ _031_;
endmodule

(* top =  1  *)
(* src = "rtl/tinymac_top.sv:12.1-91.10" *)
module tinymac_top(clk, rst_n, start, a0, a1, a2, a3, b0, b1, b2, b3, done, result);
  (* src = "rtl/tinymac_top.sv:17.25-17.27" *)
  input [7:0] a0;
  wire [7:0] a0;
  (* src = "rtl/tinymac_top.sv:18.25-18.27" *)
  input [7:0] a1;
  wire [7:0] a1;
  (* src = "rtl/tinymac_top.sv:19.25-19.27" *)
  input [7:0] a2;
  wire [7:0] a2;
  (* src = "rtl/tinymac_top.sv:20.25-20.27" *)
  input [7:0] a3;
  wire [7:0] a3;
  (* src = "rtl/tinymac_top.sv:22.25-22.27" *)
  input [7:0] b0;
  wire [7:0] b0;
  (* src = "rtl/tinymac_top.sv:23.25-23.27" *)
  input [7:0] b1;
  wire [7:0] b1;
  (* src = "rtl/tinymac_top.sv:24.25-24.27" *)
  input [7:0] b2;
  wire [7:0] b2;
  (* src = "rtl/tinymac_top.sv:25.25-25.27" *)
  input [7:0] b3;
  wire [7:0] b3;
  (* src = "rtl/tinymac_top.sv:13.25-13.28" *)
  input clk;
  wire clk;
  (* src = "rtl/tinymac_top.sv:27.25-27.29" *)
  output done;
  wire done;
  (* src = "rtl/tinymac_top.sv:31.18-31.20" *)
  wire [15:0] p0;
  (* src = "rtl/tinymac_top.sv:32.18-32.20" *)
  wire [15:0] p1;
  (* src = "rtl/tinymac_top.sv:33.18-33.20" *)
  wire [15:0] p2;
  (* src = "rtl/tinymac_top.sv:34.18-34.20" *)
  wire [15:0] p3;
  (* src = "rtl/tinymac_top.sv:28.25-28.31" *)
  output [31:0] result;
  reg [31:0] result;
  (* src = "rtl/tinymac_top.sv:37.18-37.27" *)
  wire result_en;
  (* src = "rtl/tinymac_top.sv:14.25-14.30" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/tinymac_top.sv:15.25-15.30" *)
  input start;
  wire start;
  (* src = "rtl/tinymac_top.sv:36.18-36.26" *)
  wire [31:0] sum_comb;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[0] <= 1'h0;
    else if (result_en) result[0] <= sum_comb[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[1] <= 1'h0;
    else if (result_en) result[1] <= sum_comb[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[2] <= 1'h0;
    else if (result_en) result[2] <= sum_comb[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[3] <= 1'h0;
    else if (result_en) result[3] <= sum_comb[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[4] <= 1'h0;
    else if (result_en) result[4] <= sum_comb[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[5] <= 1'h0;
    else if (result_en) result[5] <= sum_comb[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[6] <= 1'h0;
    else if (result_en) result[6] <= sum_comb[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[7] <= 1'h0;
    else if (result_en) result[7] <= sum_comb[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[8] <= 1'h0;
    else if (result_en) result[8] <= sum_comb[8];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[9] <= 1'h0;
    else if (result_en) result[9] <= sum_comb[9];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[10] <= 1'h0;
    else if (result_en) result[10] <= sum_comb[10];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[11] <= 1'h0;
    else if (result_en) result[11] <= sum_comb[11];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[12] <= 1'h0;
    else if (result_en) result[12] <= sum_comb[12];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[13] <= 1'h0;
    else if (result_en) result[13] <= sum_comb[13];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[14] <= 1'h0;
    else if (result_en) result[14] <= sum_comb[14];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[15] <= 1'h0;
    else if (result_en) result[15] <= sum_comb[15];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[16] <= 1'h0;
    else if (result_en) result[16] <= sum_comb[16];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[17] <= 1'h0;
    else if (result_en) result[17] <= sum_comb[17];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[18] <= 1'h0;
    else if (result_en) result[18] <= sum_comb[18];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[19] <= 1'h0;
    else if (result_en) result[19] <= sum_comb[19];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[20] <= 1'h0;
    else if (result_en) result[20] <= sum_comb[20];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[21] <= 1'h0;
    else if (result_en) result[21] <= sum_comb[21];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[22] <= 1'h0;
    else if (result_en) result[22] <= sum_comb[22];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[23] <= 1'h0;
    else if (result_en) result[23] <= sum_comb[23];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[24] <= 1'h0;
    else if (result_en) result[24] <= sum_comb[24];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[25] <= 1'h0;
    else if (result_en) result[25] <= sum_comb[25];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[26] <= 1'h0;
    else if (result_en) result[26] <= sum_comb[26];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[27] <= 1'h0;
    else if (result_en) result[27] <= sum_comb[27];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[28] <= 1'h0;
    else if (result_en) result[28] <= sum_comb[28];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[29] <= 1'h0;
    else if (result_en) result[29] <= sum_comb[29];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[30] <= 1'h0;
    else if (result_en) result[30] <= sum_comb[30];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:83.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result[31] <= 1'h0;
    else if (result_en) result[31] <= sum_comb[31];
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:65.16-71.6" *)
  adder_tree u_adder_tree (
    .p0(p0),
    .p1(p1),
    .p2(p2),
    .p3(p3),
    .sum(sum_comb)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:74.17-80.6" *)
  control_fsm u_control_fsm (
    .clk(clk),
    .done(done),
    .result_en(result_en),
    .rst_n(rst_n),
    .start(start)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:40.14-44.6" *)
  mac_unit u_mac0 (
    .a(a0),
    .b(b0),
    .product(p0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:46.14-50.6" *)
  mac_unit u_mac1 (
    .a(a1),
    .b(b1),
    .product(p1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:52.14-56.6" *)
  mac_unit u_mac2 (
    .a(a2),
    .b(b2),
    .product(p2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/tinymac_top.sv:58.14-62.6" *)
  mac_unit u_mac3 (
    .a(a3),
    .b(b3),
    .product(p3)
  );
endmodule
